apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: hashicorp/http-echo
        args:
          - "-text=Hello from Ravindra Jadhav, I am a RockStar Baby, Awuo...!"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: 5678

